apiVersion: v1
kind: Pod

metadata:
  name: crm-frontend
  labels:
    app: crm-frontend

spec:
  containers:
    - name: frontend
      image: singhsarvesh/crm-frontend:5
      imagePullPolicy: IfNotPresent

      ports:
        - containerPort: 5173 