apiVersion: apps/v1
kind: Deployment

metadata:
  name: crm-frontend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: crm-frontend

  template:
    metadata:
      labels:
        app: crm-frontend

    spec:
      containers:
      - name: frontend
        image: singhsarvesh/crm-frontend:7
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 5173
